# Crowdin configuration file for downloading translations only
# Source files are managed in a different repository
base_path: "../"
files:
  - source: /emhttp/languages/unraid-webgui.po
    translation: /emhttp/languages/%locale%/unraid-webgui.po
    scheme: file

  - source: /emhttp/languages/unraid-webgui-js.po
    translation: /emhttp/languages/%locale%/unraid-webgui-js.po
    scheme: file

  - source: /emhttp/languages/helptext.txt
    translation: /emhttp/languages/%locale%/helptext.txt
    scheme: file

# Export settings
export_only_approved: false
skip_untranslated_files: false
skip_untranslated_strings: false
preserve_hierarchy: false

download_translations_args: --verbose