# Crowdin configuration file for downloading translations only
# Source files are managed in a different repository

files:
  - source: /unraid-webgui.po
    translation: /unraid-webgui.po
    scheme: file
    
  - source: /unraid-webgui-js.po
    translation: /unraid-webgui-js.po
    scheme: file
    
  - source: /helptext.txt
    translation: /helptext.txt
    scheme: file

# Export settings
export_only_approved: false
skip_untranslated_files: false
skip_untranslated_strings: false
preserve_hierarchy: true