# Crowdin configuration file for downloading translations
# This file defines how translations are downloaded and organized

files:
  # Map specific files from Crowdin to local paths
  - source: /unraid-webgui.po
    translation: /%locale%/unraid-webgui.po
    
  - source: /unraid-webgui-js.po
    translation: /%locale%/unraid-webgui-js.po
    
  - source: /helptext.txt
    translation: /%locale%/helptext.txt

# Additional settings
preserve_hierarchy: true